version: "3.9"
services:

  postgres:
    image: postgres:11.6
    container_name: pgsql-todolist
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data

  web:
    restart: always
    image: web
    container_name: fastapi-todolist
    build: ./
    env_file:
      - .env
#    command: >
#      bash -c "source app/run.sh"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres