version: "3.9"
services:

  postgres:
    image: postgres:11.6
    container_name: pgsql-todolist
    volumes:
      - ./:/app/pgsql_data/

  web:
    restart: always
    image: web
    container_name: fastapi-todolist
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres